### ISSUE TITLE
@all

### ISSUE THREAD

**Issue by adeee3eb** [TTMTT/iCL0udin#2]
عندي 4 طرق وكان ودي اعرظها لكم بس في زنوات هنا حاشر لنفسه يقلطع في كل شي

**Comment by adeee3eb** [comment]
انت فاشلين واغبياء

**Comment by rAbd0u** [comment]
نريد واحدة فقط من هذه الأربعة 
ساعدنا أخي

**Comment by rAbd0u** [comment]
rafienet@yahoo.fr
